# Generated by Django 4.2.10 on 2024-03-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_subscriptioncourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='id сессии'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма оплаты'),
        ),
    ]
