# Generated by Django 4.2.10 on 2024-03-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_remove_payments_payment_type_payments_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='статус платежа'),
        ),
    ]
